
import bag from "../assets/.jpg";
const ProductData = [
  {
    id: 1,
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTNCtBpG4M3k_B7pD-l6rFywjkd3_4NQePvLLDdaVDFXXV8w0LX-2BwAVIuYVwNyHSsW3Eft9zidR0uB_dJlkgyVhh9qURhAoWGJ0KclCt5QBzqdaBR1u1nOii7rmv0M6x-uIPN5v4&usqp=CAc",
    name: "Nike Running Shoes",
    price: 2999,
    desc: "Comfortable and stylish Nike shoes designed for everyday wear and running. Made with breathable mesh and durable soles for all-day comfort.",
    category: "Clothes",
    rating: 4.5,
  },
  {
    id: 2,
    img: bag,
    price: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTNCtBpG4M3k_B7pD-l6rFywjkd3_4NQePvLLDdaVDFXXV8w0LX-2BwAVIuYVwNyHSsW3Eft9zidR0uB_dJlkgyVhh9qURhAoWGJ0KclCt5QBzqdaBR1u1nOii7rmv0M6x-uIPN5v4&usqp=CAc",
    desc: "Soft, breathable cotton t-shirt with a slim fit. Perfect for casual wear or layering under jackets.",
    category: "Clothes",
    rating: 4.3,
  },
  {
    id: 3,
    img: "https://www.pngall.com/wp-content/uploads/5/Mobile-Phone-PNG-Free-Image.png",
    name: "Smartphone (Android)",
    price: 15999,
    desc: "Latest model with high-resolution camera, long battery life, and a fast processor for smooth multitasking.",
    category: "Gadgets",
    rating: 4.7,
  },
  {
    id: 4,
    img: "https://www.pngall.com/wp-content/uploads/5/Laptop-PNG-Picture.png",
    name: "Laptop (Intel i5)",
    price: 47999,
    desc: "Powerful laptop with Intel i5 processor, 8GB RAM, and 512GB SSD – ideal for work, study, and entertainment.",
    category: "Gadgets",
    rating: 4.6,
  },
  {
    id: 5,
    img: "https://www.pngall.com/wp-content/uploads/5/Lipstick-PNG-Images.png",
    name: "Matte Lipstick",
    price: 499,
    desc: "Long-lasting matte lipstick with rich color and a smooth finish. Perfect for all-day wear.",
    category: "Cosmetics",
    rating: 4.4,
  },
  {
    id: 6,
    img: "https://www.pngall.com/wp-content/uploads/5/Perfume-PNG-Pic.png",
    name: "Luxury Perfume",
    price: 1999,
    desc: "Elegant fragrance with floral and woody notes, perfect for special occasions or daily use.",
    category: "Cosmetics",
    rating: 4.8,
  },
    {
      id: 7,
      img: "https://www.pngall.com/wp-content/uploads/5/Smart-Watch-PNG-Photo.png",
      name: "Smart Watch",
      price: 3499,
      desc: "Multifunctional smart watch with heart rate monitor and notification alerts.",
      category: "Electronics",
      rating: 4.5,
    },
    {
      id: 8,
      img: "https://www.pngall.com/wp-content/uploads/5/Wireless-Earbuds-PNG-Clipart.png",
      name: "Wireless Earbuds",
      price: 1999,
      desc: "Compact Bluetooth earbuds with noise cancellation and long battery life.",
      category: "Electronics",
      rating: 4.6,
    },
    {
      id: 9,
      img: "https://www.pngall.com/wp-content/uploads/5/Sunscreen-PNG.png",
      name: "SPF 50 Sunscreen",
      price: 599,
      desc: "Protective sunscreen for all skin types. Non-greasy and water-resistant.",
      category: "Cosmetics",
      rating: 4.2,
    },
    {
      id: 10,
      img: "https://www.pngall.com/wp-content/uploads/5/Headphones-PNG-High-Quality-Image.png",
      name: "Over-Ear Headphones",
      price: 2499,
      desc: "High-quality stereo sound with adjustable band and soft ear cushions.",
      category: "Electronics",
      rating: 4.4,
    },
    {
      id: 11,
      img: "https://www.pngall.com/wp-content/uploads/5/Denim-Jacket-PNG.png",
      name: "Men’s Denim Jacket",
      price: 2099,
      desc: "Classic denim jacket for casual outfits. Durable and stylish.",
      category: "Clothing",
      rating: 4.3,
    },
    {
      id: 12,
      img: "https://www.pngall.com/wp-content/uploads/5/Makeup-Kit-PNG-HD-Image.png",
      name: "Makeup Kit",
      price: 1499,
      desc: "All-in-one makeup kit with eyeshadow, blush, and lipstick.",
      category: "Cosmetics",
      rating: 4.5,
    },
    {
      id: 13,
      img: "https://www.pngall.com/wp-content/uploads/5/Sneakers-PNG-HD-Image.png",
      name: "Unisex Sneakers",
      price: 2899,
      desc: "Comfortable sneakers with cushioned soles and breathable mesh.",
      category: "Clothing",
      rating: 4.7,
    },
    {
      id: 14,
      img: "https://www.pngall.com/wp-content/uploads/5/Face-Cream-PNG-Photos.png",
      name: "Hydrating Face Cream",
      price: 749,
      desc: "Moisturizer with aloe vera and vitamin E for radiant skin.",
      category: "Cosmetics",
      rating: 4.4,
    },
    {
      id: 15,
      img: "https://www.pngall.com/wp-content/uploads/5/Tablet-PNG-Free-Image.png",
      name: "Android Tablet",
      price: 10999,
      desc: "Portable tablet with 10-inch display and fast quad-core processor.",
      category: "Electronics",
      rating: 4.3,
    },
    {
      id: 16,
      img: leatherHandbag,
      name: "Leather Handbag",
      price: 1899,
      desc: "Chic leather handbag for everyday use with ample storage.",
      category: "Clothing",
      rating: 4.6,
      
    },
    
    {
      id: 17,
      img: "https://www.pngall.com/wp-content/uploads/5/Powerbank-PNG-HD-Image.png",
      name: "10000mAh Power Bank",
      price: 1199,
      desc: "High-capacity power bank with dual USB output.",
      category: "Electronics",
      rating: 4.5,
    },
    {
      id: 18,
      img: "https://www.pngall.com/wp-content/uploads/5/Nail-Polish-PNG-File.png",
      name: "Gel Nail Polish Set",
      price: 499,
      desc: "Vibrant, long-lasting nail polish with salon-like finish.",
      category: "Cosmetics",
      rating: 4.1,
    },
    {
      id: 19,
      img: "https://www.pngall.com/wp-content/uploads/5/Women-T-Shirt-PNG-Photo.png",
      name: "Women's Graphic Tee",
      price: 699,
      desc: "Trendy t-shirt with cool printed design, made of soft cotton.",
      category: "Clothing",
      rating: 4.3,
    },
    {
      id: 20,
      img: "https://www.pngall.com/wp-content/uploads/5/Laptop-Bag-PNG-Free-Download.png",
      name: "Laptop Backpack",
      price: 1599,
      desc: "Water-resistant backpack with multiple compartments.",
      category: "Clothing",
      rating: 4.4,
    },
    {
      id: 21,
      img: "https://www.pngall.com/wp-content/uploads/5/Eye-Makeup-PNG.png",
      name: "Eye Shadow Palette",
      price: 899,
      desc: "Palette with 24 vibrant shades for bold or natural looks.",
      category: "Cosmetics",
      rating: 4.6,
    },
    {
      id: 22,
      img: "https://www.pngall.com/wp-content/uploads/5/Camera-PNG-HD-Image.png",
      name: "DSLR Camera",
      price: 45999,
      desc: "High-resolution DSLR with interchangeable lenses.",
      category: "Electronics",
      rating: 4.8,
    },
    {
      id: 23,
      img: "https://www.pngall.com/wp-content/uploads/5/Men-Shoes-PNG-High-Quality-Image.png",
      name: "Men’s Formal Shoes",
      price: 2299,
      desc: "Elegant leather shoes ideal for office or formal events.",
      category: "Clothing",
      rating: 4.2,
    },
    {
      id: 24,
      img: "https://www.pngall.com/wp-content/uploads/5/Hair-Dryer-PNG-Image.png",
      name: "Compact Hair Dryer",
      price: 999,
      desc: "Quick-dry hairdryer with 2 heat settings and foldable design.",
      category: "Electronics",
      rating: 4.4,
    },
    {
      id: 25,
      img: "https://www.pngall.com/wp-content/uploads/5/Face-Wash-PNG.png",
      name: "Refreshing Face Wash",
      price: 349,
      desc: "Foaming face wash that removes dirt and oil instantly.",
      category: "Cosmetics",
      rating: 4.1,
    },
    {
      id: 26,
      img: "https://www.pngall.com/wp-content/uploads/5/Women-Shoes-PNG-Image.png",
      name: "Women's Ballet Flats",
      price: 1299,
      desc: "Comfortable slip-on flats with cushioned insole.",
      category: "Clothing",
      rating: 4.5,
    },
    {
      id: 27,
      img: "https://www.pngall.com/wp-content/uploads/5/Shaver-PNG-Image.png",
      name: "Electric Beard Trimmer",
      price: 1199,
      desc: "Rechargeable trimmer with precision blades.",
      category: "Electronics",
      rating: 4.6,
    },
    {
      id: 28,
      img: "https://www.pngall.com/wp-content/uploads/5/Women-Perfume-PNG.png",
      name: "Floral Perfume",
      price: 1699,
      desc: "Elegant perfume with sweet floral notes for daily wear.",
      category: "Cosmetics",
      rating: 4.5,
    },
    {
      id: 29,
      img: "https://www.pngall.com/wp-content/uploads/5/Jeans-PNG-Image.png",
      name: "Slim Fit Jeans",
      price: 1499,
      desc: "Stretchable slim fit jeans in dark wash denim.",
      category: "Clothing",
      rating: 4.2,
    },
    {
      id: 30,
      img: "https://www.pngall.com/wp-content/uploads/5/Bluetooth-Speaker-PNG-Picture.png",
      name: "Bluetooth Speaker",
      price: 1799,
      desc: "Portable wireless speaker with deep bass and 10h playtime.",
      category: "Electronics",
      rating: 4.7,
    },
      {
        id: 101,
        img: "https://images.samsung.com/is/image/samsung/assets/us/watches/galaxy-watch3/images/gallery/galaxy-watch3-01.png",
        name: "Samsung Galaxy Watch3",
        price: 399.99,
        desc: "Smartwatch with health monitoring and rotating bezel.",
        category: "Electronics",
        rating: 4.6,
      },
      {
        id: 102,
        img: "https://www.sony.com/image/1cdd6354c4cd21cc4f7ec78f9e9ad165?fmt=pjpeg&wid=660&hei=660&bgcolor=F1F5F9&bgc=F1F5F9",
        name: "Sony WH-1000XM4 Headphones",
        price: 349.99,
        desc: "Wireless noise-canceling headphones with touch controls.",
        category: "Electronics",
        rating: 4.8,
      },
      {
        id: 103,
        img: "https://www.fitbit.com/global/content/dam/fitbit/global/pdp/charge-4/hero/PDP-Charge-4-Black-Hero.png",
        name: "Fitbit Charge 4",
        price: 129.95,
        desc: "Fitness tracker with GPS and heart rate monitoring.",
        category: "Electronics",
        rating: 4.5,
      },
      {
        id: 104,
        img: "https://dummyjson.com/image/i/products/1/1.jpg",
        name: "iPhone 9",
        price: 549,
        desc: "An apple mobile which is nothing like apple.",
        category: "Electronics",
        rating: 4.69,
      },
      {
        id: 105,
        img: "https://dummyjson.com/image/i/products/2/1.jpg",
        name: "Samsung Galaxy Book",
        price: 1499,
        desc: "Samsung's new variant which goes beyond Galaxy to the Universe.",
        category: "Electronics",
        rating: 4.25,
      },
      {
        id: 106,
        img: "https://dummyjson.com/image/i/products/4/1.jpg",
        name: "OPPO F19",
        price: 280,
        desc: "OPPO F19 is officially announced on April 2021.",
        category: "Electronics",
        rating: 4.3,
      },
      {
        id: 107,
        img: "https://dummyjson.com/image/i/products/6/1.png",
        name: "MacBook Pro",
        price: 1749,
        desc: "MacBook Pro 2021 with mini-LED display may launch between September, November.",
        category: "Electronics",
        rating: 4.57,
      },
      {
        id: 108,
        img: "https://dummyjson.com/image/i/products/10/1.jpg",
        name: "Huawei P30",
        price: 499,
        desc: "Huawei’s re-badged P30 Pro New Edition was officially unveiled in Germany.",
        category: "Electronics",
        rating: 4.09,
      },
      {
        id: 109,
        img: "https://dummyjson.com/image/i/products/14/1.jpg",
        name: "Samsung Galaxy A31",
        price: 280,
        desc: "Samsung Galaxy A31 is officially announced on March 2020.",
        category: "Electronics",
        rating: 4.3,
      },
      {
        id: 110,
        img: "https://dummyjson.com/image/i/products/15/1.jpg",
        name: "Motorola Edge",
        price: 999,
        desc: "Motorola Edge offers a curved display and 5G support.",
        category: "Electronics",
        rating: 4.5,
      },
      {
        id: 111,
        img: "https://dummyjson.com/image/i/products/17/1.jpg",
        name: "Samsung Galaxy S20",
        price: 699,
        desc: "Samsung Galaxy S20 is powered by Exynos 990 processor.",
        category: "Electronics",
        rating: 4.7,
      },
      {
        id: 112,
        img: "https://dummyjson.com/image/i/products/18/1.jpg",
        name: "Xiaomi Mi 10",
        price: 399,
        desc: "Xiaomi Mi 10 features a 108MP camera and Snapdragon 865.",
        category: "Electronics",
        rating: 4.6,
      },
      {
        id: 113,
        img: "https://dummyjson.com/image/i/products/19/1.jpg",
        name: "OnePlus 8",
        price: 699,
        desc: "OnePlus 8 comes with a 90Hz display and 5G support.",
        category: "Electronics",
        rating: 4.5,
      },
      {
        id: 114,
        img: "https://dummyjson.com/image/i/products/20/1.jpg",
        name: "Google Pixel 5",
        price: 699,
        desc: "Google Pixel 5 features a 6-inch OLED display and 5G.",
        category: "Electronics",
        rating: 4.4,
      },
      {
        id: 115,
        img: "https://dummyjson.com/image/i/products/21/1.jpg",
        name: "LG Velvet",
        price: 599,
        desc: "LG Velvet offers a sleek design with dual-screen support.",
        category: "Electronics",
        rating: 4.3,
      },
      {
        id: 116,
        img: "https://dummyjson.com/image/i/products/22/1.jpg",
        name: "Nokia 8.3 5G",
        price: 649,
        desc: "Nokia 8.3 5G is a global 5G smartphone with ZEISS optics.",
        category: "Electronics",
        rating: 4.2,
      },
      {
        id: 117,
        img: "https://dummyjson.com/image/i/products/23/1.jpg",
        name: "Sony Xperia 5 II",
        price: 949,
        desc: "Sony Xperia 5 II features a 120Hz display and triple camera.",
        category: "Electronics",
        rating: 4.5,
      },
        {
          id: 301,
          img: "https://www.pngall.com/wp-content/uploads/5/Nike-Shoe-PNG.png",
          name: "Nike Air Zoom Pegasus",
          price: 3999,
          desc: "Lightweight running shoes with breathable mesh and responsive cushioning.",
          category: "Shoes",
          rating: 4.7,
        },
        {
          id: 302,
          img: "https://www.pngall.com/wp-content/uploads/5/Running-Shoes-PNG-Image-HD.png",
          name: "Adidas Ultraboost",
          price: 5999,
          desc: "High-performance running shoes with energy-returning Boost midsole.",
          category: "Shoes",
          rating: 4.8,
        },
        {
          id: 303,
          img: "https://www.pngall.com/wp-content/uploads/5/Sneakers-PNG-Pic.png",
          name: "Puma Smash V2",
          price: 2999,
          desc: "Stylish sneakers for everyday casual wear.",
          category: "Shoes",
          rating: 4.5,
        },
        {
          id: 304,
          img: "https://www.pngall.com/wp-content/uploads/5/Reebok-Shoes-PNG-HD-Image.png",
          name: "Reebok Classic",
          price: 3499,
          desc: "Retro-style sneakers with soft leather upper and cushioned midsole.",
          category: "Shoes",
          rating: 4.6,
        },
        {
          id: 305,
          img: "https://www.pngall.com/wp-content/uploads/5/Sports-Shoes-PNG-Free-Image.png",
          name: "ASICS Gel-Kayano",
          price: 6799,
          desc: "Stability running shoes with Gel cushioning for shock absorption.",
          category: "Shoes",
          rating: 4.9,
        },
        {
          id: 306,
          img: "https://www.pngall.com/wp-content/uploads/5/Jogging-Shoes-PNG-Free-Download.png",
          name: "New Balance 574",
          price: 4199,
          desc: "Classic sneakers blending retro looks with modern comfort.",
          category: "Shoes",
          rating: 4.6,
        },
        {
          id: 307,
          img: "https://www.pngall.com/wp-content/uploads/5/Men-Shoes-PNG-Free-Image.png",
          name: "Converse Chuck Taylor",
          price: 2899,
          desc: "Iconic canvas sneakers suitable for casual wear.",
          category: "Shoes",
          rating: 4.4,
        },
        {
          id: 308,
          img: "https://www.pngall.com/wp-content/uploads/5/Leather-Shoes-PNG-Clipart.png",
          name: "Clarks Leather Formal",
          price: 4999,
          desc: "Premium leather formal shoes for office or events.",
          category: "Shoes",
          rating: 4.5,
        },
        {
          id: 309,
          img: "https://www.pngall.com/wp-content/uploads/5/Black-Shoes-PNG-Image.png",
          name: "Bata Executive Loafers",
          price: 2499,
          desc: "Comfortable and durable slip-on loafers for daily wear.",
          category: "Shoes",
          rating: 4.2,
        },
        {
          id: 310,
          img: "https://www.pngall.com/wp-content/uploads/5/Winter-Boots-PNG-HD.png",
          name: "Woodland Leather Boots",
          price: 5699,
          desc: "Rugged leather boots ideal for trekking and winter wear.",
          category: "Shoes",
          rating: 4.7,
        },
        {
          id: 311,
          img: "https://www.pngall.com/wp-content/uploads/5/Sneakers-PNG-Image-HD.png",
          name: "Fila Disruptor II",
          price: 3799,
          desc: "Chunky sneakers with bold streetwear style.",
          category: "Shoes",
          rating: 4.3,
        },
        {
          id: 312,
          img: "https://www.pngall.com/wp-content/uploads/5/Heels-PNG-Pic.png",
          name: "H&M Block Heels",
          price: 1899,
          desc: "Elegant block heels perfect for formal occasions.",
          category: "Shoes",
          rating: 4.4,
        },
        {
          id: 313,
          img: "https://www.pngall.com/wp-content/uploads/5/Slippers-PNG-Image.png",
          name: "Relaxo Flip Flops",
          price: 499,
          desc: "Lightweight and comfy flip-flops for indoor/outdoor use.",
          category: "Shoes",
          rating: 4.0,
        },
        {
          id: 314,
          img: "https://www.pngall.com/wp-content/uploads/5/Ankle-Boots-PNG-Image.png",
          name: "Zara Ankle Boots",
          price: 3999,
          desc: "Trendy ankle boots for fashionable everyday wear.",
          category: "Shoes",
          rating: 4.5,
        },
        {
          id: 315,
          img: "https://www.pngall.com/wp-content/uploads/5/Kids-Shoes-PNG-Free-Download.png",
          name: "Skechers Kids Running",
          price: 2199,
          desc: "Durable, flexible kids' running shoes with bright colors.",
          category: "Shoes",
          rating: 4.6,
        }
      ];
      

export default ProductData;
